
2021-02-12 07:39:38,430 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 07:39:38] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-12 11:47:09,908 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database
2021-02-12 11:47:09,909 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_database' 
2021-02-12 11:47:09,910 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 12:03:18,898 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-12 12:03:18,900 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-12 12:03:18,942 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-12 12:04:04,217 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 12:04:04,218 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 54, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 12:04:04,220 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 22 
2021-02-12 12:04:04,220 - signal_interpreter_server.json_parser - INFO - Aborting server ... %s
2021-02-12 12:04:04,222 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 12:04:04] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-12 12:04:16,968 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 12:04:16] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 12:06:54,454 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-12 12:06:54,455 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-12 12:06:54,494 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-12 12:07:13,381 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 12:07:13] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 12:07:26,993 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 12:07:26,994 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 54, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 12:07:26,995 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 22 
2021-02-12 12:07:26,996 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 12:07:26,997 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 12:07:26] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-12 12:11:47,257 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-12 12:11:47,258 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-12 12:11:47,297 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-12 12:11:55,755 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 12:11:55,756 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 12:11:55,758 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 22 
2021-02-12 12:11:55,758 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 12:11:55,759 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 12:11:55] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-12 12:12:09,575 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 12:12:09] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 12:12:23,118 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_databas
2021-02-12 12:12:23,119 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databas' 
2021-02-12 12:12:23,120 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:33:04,209 - signal_interpreter_server.json_parser - INFO - Opening json database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.json
2021-02-12 16:33:04,211 - signal_interpreter_server.json_parser - INFO - Loading json database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.json
2021-02-12 16:33:16,035 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:33:16,041 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:33:16,065 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:33:16,066 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:33:16,067 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:33:16,069 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:42:04,137 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:42:04,141 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:44:21,230 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:44:21,236 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:44:21,260 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:44:21,261 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 45, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:44:21,264 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:44:21,265 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:44:50,187 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:44:50,191 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:48:09,046 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:48:09,049 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:48:09,067 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:48:09,067 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:48:09,071 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:48:09,080 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:50:21,663 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:50:21,669 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:50:21,688 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:50:21,690 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:50:21,693 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:50:21,703 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:51:48,252 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:51:48,258 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:51:48,282 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:51:48,282 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:51:48,285 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:51:48,286 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:54:03,171 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:54:03,176 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:54:03,182 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:54:03,183 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:54:03,186 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:54:03,187 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:56:08,230 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:56:08,235 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:56:08,256 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:56:08,258 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:56:08,261 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:56:08,262 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:58:01,321 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:58:01,327 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:58:01,350 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:58:01,351 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:58:01,353 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:58:01,362 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 16:58:53,407 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 16:58:53,412 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 16:58:53,431 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 16:58:53,432 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 45, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 16:58:53,434 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 16:58:53,444 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:21:21,303 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-12 17:21:21,305 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-12 17:21:21,343 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-12 17:21:29,502 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 17:21:29] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 17:22:07,347 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:22:07,351 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:22:07,371 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:22:07,372 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:22:07,374 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:22:07,383 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:47:46,316 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:47:46,321 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:47:46,330 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:47:46,332 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:47:46,349 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:47:46,350 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:47:46,352 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:47:46,354 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:48:41,694 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:48:41,698 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:48:41,872 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:48:41,872 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 44, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:48:41,875 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:48:41,876 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:49:50,285 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:49:50,291 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:49:50,435 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:49:50,435 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 46, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:49:50,437 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:49:50,445 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:51:04,337 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:51:04,342 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:51:04,467 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:51:04,468 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 46, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:51:04,470 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:51:04,478 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:54:23,215 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:54:23,219 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:54:23,342 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:54:23,343 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 46, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:54:23,344 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:54:23,352 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 17:56:13,308 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 17:56:13,312 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 17:56:13,420 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 17:56:13,421 - signal_interpreter_server.json_parser - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\json_parser.py", line 46, in get_signal_title
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 17:56:13,423 - signal_interpreter_server.json_parser - ERROR - Requested signal not found in database, signal ID: 20 
2021-02-12 17:56:13,432 - signal_interpreter_server.json_parser - INFO - Aborting server ...
2021-02-12 18:18:35,866 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 18:18:35,872 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 18:20:41,966 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 18:20:41,970 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 18:23:32,050 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 18:23:32,053 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 18:32:25,827 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_databas
2021-02-12 18:32:25,829 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databas' 
2021-02-12 18:32:25,829 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 18:32:33,774 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-12 18:32:33,776 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-12 18:32:33,806 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-12 18:32:42,915 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 18:32:42] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 18:32:49,197 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 18:32:49,198 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 18:32:49,199 - signal_interpreter_server.routes - ERROR - Requested signal not found in database, signal ID: 22 
2021-02-12 18:32:49,200 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 18:32:49,200 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 18:32:49] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 19:05:09,566 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_databas
2021-02-12 19:05:09,567 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databas' 
2021-02-12 19:05:09,567 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:05:25,120 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-12 19:05:25,122 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-12 19:05:25,163 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-12 19:05:29,456 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:05:29,457 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:05:29,459 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-12 19:05:29,459 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:05:29,460 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 19:05:29] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-12 19:05:36,026 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 19:05:36] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-12 19:05:44,436 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:05:44,437 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:05:44,439 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-12 19:05:44,439 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:05:44,441 - werkzeug - INFO - 127.0.0.1 - - [12/Feb/2021 19:05:44] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-12 19:06:18,894 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:06:18,899 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:12:23,577 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:12:23,582 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:14:40,812 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:14:40,817 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:15:32,420 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:15:32,425 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:17:26,326 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:17:26,331 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:17:48,133 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:17:48,139 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:20:39,249 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:20:39,253 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:22:43,108 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:22:43,112 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:23:50,760 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:23:50,763 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:23:50,824 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:23:50,825 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:23:50,827 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:23:50,828 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:24:37,156 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:24:37,160 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:24:37,221 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:24:37,221 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:24:37,223 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:24:37,223 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:26:01,198 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:26:01,202 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:26:35,790 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:26:35,794 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:28:31,493 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:28:31,497 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:28:31,575 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:28:31,576 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:28:31,579 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:28:31,580 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:28:45,753 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:28:45,757 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:28:45,822 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:28:45,824 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:28:45,826 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:28:45,827 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:32:28,920 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:32:28,924 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:32:28,992 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:32:28,993 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:32:28,995 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:32:28,996 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:34:33,877 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:34:33,881 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:34:33,943 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:34:33,944 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:34:33,946 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:34:33,946 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:34:51,849 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:34:51,853 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:34:51,915 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:34:51,916 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:34:51,918 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:34:51,918 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:35:56,882 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:35:56,888 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:35:56,951 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:35:56,952 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:35:56,954 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:35:56,954 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:37:41,930 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:37:41,936 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:37:42,012 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:37:42,013 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:37:42,017 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:37:42,017 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:38:48,768 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:38:48,772 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:38:48,835 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:38:48,836 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:38:48,838 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:38:48,838 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:39:35,227 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:39:35,230 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:39:35,292 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 19:39:35,293 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-12 19:39:35,296 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-12 19:39:35,296 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-12 19:40:41,275 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:40:41,280 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:44:41,762 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:44:41,767 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:47:33,336 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:47:33,339 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:47:48,855 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:47:48,858 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:48:25,204 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:48:25,209 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:52:43,252 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:52:43,256 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:59:30,167 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:59:30,171 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 19:59:30,177 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 19:59:30,178 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-12 19:59:30,179 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 20:11:05,317 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:11:05,321 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:14:36,210 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:14:36,214 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:15:46,606 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:15:46,611 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:17:33,493 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:17:33,498 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:19:56,403 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:19:56,407 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:20:12,937 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_databas
2021-02-12 20:20:12,938 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databas' 
2021-02-12 20:20:12,939 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-12 20:31:56,753 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:31:56,756 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:45:42,339 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:45:42,342 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-12 20:46:58,361 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-12 20:46:58,364 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:06:35,232 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:06:35,234 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:18:29,788 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:18:29,790 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:18:29,794 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:18:29,794 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:18:29,795 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:22:20,371 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:22:20,374 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:22:43,821 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:22:43,824 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:25:22,231 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:25:22,233 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:25:46,978 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:25:46,981 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:27:35,725 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:27:35,727 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:27:35,731 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:27:35,731 - signal_interpreter_server.json_parser - WARNING - Exception occurred  
2021-02-13 12:27:35,731 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:30:14,609 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:30:14,611 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:31:08,224 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:31:08,226 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:31:08,230 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:31:08,230 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:31:08,231 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:31:33,772 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:31:33,775 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:32:06,608 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:32:06,610 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:32:06,614 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:32:06,614 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:32:06,614 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:35:53,076 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:35:53,078 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:35:53,079 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:35:53,079 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:35:53,079 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:36:45,287 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:36:45,289 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:36:45,290 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:36:45,290 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:36:45,291 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:38:54,124 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:38:54,126 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:38:54,127 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:38:54,127 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:38:54,127 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:56:54,537 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:56:54,539 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:56:54,539 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:56:54,540 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:56:54,540 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 12:57:19,718 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:57:19,720 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 12:57:19,721 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 12:57:19,721 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 12:57:19,722 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:00:15,891 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:00:15,893 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:00:15,894 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:00:15,894 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:00:15,894 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:00:22,156 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:00:22,158 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:00:22,159 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:00:22,159 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:00:22,159 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:02:00,474 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:02:00,476 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:02:00,477 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:02:00,477 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:02:00,477 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:09:18,357 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:09:18,359 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:09:18,360 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:09:18,360 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:09:18,361 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:09:18,394 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:09:18,394 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:09:18,395 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:09:18,395 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:11:24,249 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:11:24,251 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:11:24,252 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:11:24,252 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:11:24,253 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:11:24,287 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:11:24,287 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:11:24,288 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:11:24,288 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:14:10,523 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:14:10,524 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:14:10,526 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:14:10,526 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:14:10,526 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:14:10,560 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:14:10,560 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:14:10,561 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:14:10,561 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:14:10,562 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:14:10,562 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:14:10,562 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:14:10,563 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:15:49,055 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:15:49,057 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:15:49,058 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:15:49,058 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:15:49,058 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:15:49,090 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:15:49,090 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:15:49,091 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:15:49,092 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:15:49,092 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:15:49,092 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:15:49,093 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:15:49,093 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:16:44,571 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:16:44,573 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:16:44,574 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:16:44,574 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:16:44,574 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:16:44,614 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:16:44,615 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:16:44,616 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:16:44,617 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:16:44,617 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:16:44,618 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:16:44,618 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:16:44,618 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:17:26,367 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:17:26,369 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:17:26,370 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:17:26,370 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:17:26,370 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:17:26,404 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:17:26,404 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:17:26,405 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:17:26,406 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:17:26,406 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:17:26,407 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:17:26,407 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:17:26,407 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:20:14,463 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:20:14,465 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:20:14,466 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:20:14,466 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:20:14,466 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:20:14,500 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:20:14,501 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:20:14,502 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:20:14,502 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:21:06,787 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:21:06,789 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:21:06,789 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:21:06,790 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:21:06,790 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:21:06,821 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:21:06,822 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:21:06,823 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:21:06,823 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:22:52,743 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:22:52,745 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:22:52,746 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:22:52,746 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:22:52,746 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:22:52,780 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:22:52,780 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:22:52,782 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:22:52,782 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:27:22,056 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:27:22,058 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:27:22,060 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:27:22,061 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:27:22,061 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:27:22,092 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:27:22,093 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:27:22,094 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:27:22,094 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:27:22,100 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:27:22,101 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:27:22,101 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:27:22,102 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:28:59,013 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:28:59,016 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:28:59,017 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:28:59,017 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:28:59,017 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:28:59,053 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:28:59,053 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:28:59,054 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:28:59,055 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:29:09,335 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:29:09,337 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:29:09,338 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:29:09,338 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:29:09,339 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:29:09,377 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:29:09,377 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:29:09,378 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:29:09,379 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:33:37,530 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:33:37,533 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:33:37,533 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:33:37,534 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:33:37,534 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:33:37,568 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:33:37,568 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:33:37,569 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:33:37,569 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:34:55,015 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:34:55,017 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:34:55,017 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:34:55,018 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:34:55,018 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:34:55,049 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:34:55,049 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:34:55,050 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:34:55,050 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:35:11,809 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:35:11,811 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:35:11,811 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:35:11,811 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:35:11,812 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:35:11,844 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:35:11,845 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:35:11,846 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:35:11,846 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:35:24,692 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:35:24,694 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:35:24,695 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:35:24,695 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:35:24,696 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:35:24,723 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:35:24,724 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:35:24,725 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:35:24,725 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:38:20,632 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:38:20,634 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:38:20,635 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:38:20,635 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:38:20,636 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:38:55,305 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:38:55,307 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:38:55,308 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:38:55,308 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:38:55,308 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:38:55,341 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:38:55,342 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:38:55,342 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:38:55,343 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:40:58,172 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:40:58,174 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:40:58,175 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:40:58,175 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:40:58,175 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:40:58,207 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:40:58,207 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:40:58,208 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:40:58,209 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:41:41,178 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:41:41,180 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:41:41,181 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:41:41,181 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:41:41,181 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:41:41,212 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:41:41,212 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:41:41,213 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:41:41,213 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:46:34,847 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:46:34,849 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:46:34,850 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:46:34,850 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:46:34,850 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:46:53,491 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:46:53,493 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:46:53,493 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:46:53,494 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:46:53,494 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:47:01,892 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:47:01,894 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:47:01,895 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:47:01,895 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:47:01,895 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:47:12,535 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:47:12,537 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:47:12,538 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:47:12,538 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:47:12,538 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:47:12,573 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:47:12,573 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:47:12,575 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:47:12,575 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:47:30,440 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:47:30,442 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:47:30,443 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:47:30,443 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:47:30,444 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:47:30,475 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:47:30,475 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:47:30,476 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:47:30,476 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:48:13,621 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-13 13:48:13,622 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-13 13:48:13,638 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-13 13:48:21,092 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:48:21,092 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:48:21,093 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-13 13:48:21,093 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:48:21,094 - werkzeug - INFO - 127.0.0.1 - - [13/Feb/2021 13:48:21] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-13 13:48:26,032 - werkzeug - INFO - 127.0.0.1 - - [13/Feb/2021 13:48:26] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-13 13:48:53,205 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_databas
2021-02-13 13:48:53,205 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databas' 
2021-02-13 13:48:53,206 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:50:22,227 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:50:22,229 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:50:22,230 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:50:22,230 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:50:22,231 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:50:22,261 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:50:22,262 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:50:22,262 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:50:22,263 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 13:51:44,622 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:51:44,626 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 13:51:44,628 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 13:51:44,628 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 13:51:44,629 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:51:44,685 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 13:51:44,685 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 13:51:44,687 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 13:51:44,688 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:06:06,371 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:06:06,374 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:06:06,374 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:06:06,375 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:06:06,375 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:06:06,406 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:06:06,406 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:06:06,408 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:06:06,408 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:06:06,409 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:06:06,409 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:06:06,410 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:06:06,410 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:07:05,705 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:07:05,707 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:07:05,707 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:07:05,708 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:07:05,708 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:07:47,514 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:07:47,516 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:07:47,517 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:07:47,518 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:07:47,518 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:08:09,721 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:08:09,723 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:08:09,723 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:08:09,724 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:08:09,724 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:08:09,755 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:08:09,756 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:08:09,757 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:08:09,757 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:08:09,758 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:08:09,758 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:08:09,759 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:08:09,759 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:10:18,086 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:10:18,089 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:10:18,090 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:10:18,090 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:10:18,090 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:10:18,129 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:10:18,130 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:10:18,132 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:10:18,132 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:10:18,133 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:10:18,133 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:10:18,134 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:10:18,134 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:10:59,772 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:10:59,774 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:10:59,775 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:10:59,775 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:10:59,776 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:10:59,808 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:10:59,809 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:10:59,810 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:10:59,810 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:10:59,811 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:10:59,811 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:10:59,812 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:10:59,812 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:12:04,240 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:12:04,242 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:12:04,243 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:12:04,243 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:12:04,243 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:12:04,271 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:12:04,271 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:12:04,274 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:12:04,274 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:12:04,279 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:12:04,280 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:12:04,280 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:12:04,280 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:12:59,756 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:12:59,758 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:12:59,758 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:12:59,759 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:12:59,759 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:12:59,790 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:12:59,790 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:12:59,791 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:12:59,791 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:12:59,792 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:12:59,793 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:12:59,793 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:12:59,793 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:18:06,097 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:18:06,100 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:18:06,100 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:18:06,101 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:18:06,101 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:18:06,131 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:18:06,131 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:18:06,132 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:18:06,133 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 14:18:23,015 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:18:23,017 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 14:18:23,018 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 14:18:23,018 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 14:18:23,019 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:18:23,057 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 14:18:23,057 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 14:18:23,058 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 14:18:23,058 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 20:09:57,537 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 20:09:57,539 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 20:09:57,540 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 20:09:57,541 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 20:09:57,541 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 20:09:57,571 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 20:09:57,571 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 20:09:57,572 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 20:09:57,572 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-13 20:13:24,709 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-13 20:13:24,710 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-13 20:13:24,726 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-13 20:18:17,138 - signal_interpreter_server.json_parser - INFO - Opening json database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.json
2021-02-13 20:18:17,139 - signal_interpreter_server.json_parser - INFO - Loading json database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.json
2021-02-13 20:18:17,160 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 20:18:17,160 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-13 20:18:17,161 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-13 20:18:17,161 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-13 20:18:17,161 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 20:18:17,188 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-13 20:18:17,188 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-13 20:18:17,189 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-13 20:18:17,189 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-14 18:22:00,550 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-14 18:22:00,555 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-14 18:22:00,557 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-14 18:22:00,557 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-14 18:22:00,558 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-14 18:22:00,630 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-14 18:22:00,631 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-14 18:22:00,634 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-14 18:22:00,635 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-17 05:19:26,032 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-17 05:19:26,035 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-17 05:19:26,036 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-17 05:19:26,037 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-17 05:19:26,037 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-17 05:19:26,083 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-17 05:19:26,083 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-17 05:19:26,085 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-17 05:19:26,086 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-17 05:21:03,774 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-17 05:21:03,776 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-17 05:21:03,812 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-17 05:21:17,998 - werkzeug - INFO - 127.0.0.1 - - [17/Feb/2021 05:21:17] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-17 05:21:24,438 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-17 05:21:24,439 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-17 05:21:24,440 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-17 05:21:24,440 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-17 05:21:24,441 - werkzeug - INFO - 127.0.0.1 - - [17/Feb/2021 05:21:24] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-18 18:20:03,823 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 18:20:03,824 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 18:20:03,845 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 18:20:13,882 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-18 18:20:13,883 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 24, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-18 18:20:13,884 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-18 18:20:13,884 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-18 18:20:13,885 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 18:20:13] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-18 19:23:48,008 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.xml
2021-02-18 19:23:48,009 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.xml
2021-02-18 19:24:14,377 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:25:14,603 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:25:55,826 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:32:05,600 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:39:51,293 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:39:54,499 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:42:04,835 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 19:42:10,028 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_databa.xml
2021-02-18 19:42:10,029 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databa.xml' 
2021-02-18 19:42:10,029 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-18 20:25:23,485 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_databa.xml
2021-02-18 20:25:23,486 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'signal_databa.xml' 
2021-02-18 20:25:23,487 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-18 20:25:42,715 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 20:25:54,699 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 20:25:54,700 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 21:29:36,737 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 21:29:36,738 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 21:29:36,752 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 21:30:00,229 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 19, in interpret_signal
    signal_title = parser_factory.get_signal_title(id_of_requested_signal)
AttributeError: 'ParserFactory' object has no attribute 'get_signal_title'
2021-02-18 21:30:00,234 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 21:30:00] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 21:32:27,774 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 21:32:27,791 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 21:32:37,683 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 19, in interpret_signal
    signal_title = parser_factory.get_signal_title(id_of_requested_signal)
AttributeError: 'ParserFactory' object has no attribute 'get_signal_title'
2021-02-18 21:32:37,688 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 21:32:37] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 21:32:48,399 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 21:32:48,400 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 21:32:48,414 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 21:32:53,963 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 19, in interpret_signal
    signal_title = parser_factory.get_signal_title(id_of_requested_signal)
AttributeError: 'ParserFactory' object has no attribute 'get_signal_title'
2021-02-18 21:32:53,966 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 21:32:53] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 21:49:52,712 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 21:49:52,713 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 21:49:52,731 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 21:49:58,739 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    signal_title = signal_interpreter_server.main.parser.get_signal_title(id_of_requested_signal)
AttributeError: module 'signal_interpreter_server' has no attribute 'main'
2021-02-18 21:49:58,742 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 21:49:58] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 21:56:49,371 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 21:56:49,371 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 21:56:49,387 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 21:56:53,123 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 19, in interpret_signal
    signal_title = parser_factory.get_parser().get_signal_title(id_of_requested_signal)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 21:56:53,127 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 21:56:53] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:03:06,234 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 22:03:06,235 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 22:03:06,250 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:03:11,360 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    signal_title = signal_interpreter_server.main.factory.get_parser.get_signal_title(id_of_requested_signal)
AttributeError: module 'signal_interpreter_server' has no attribute 'main'
2021-02-18 22:03:11,363 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:03:11] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:05:17,688 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 22:05:17,688 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 22:05:17,703 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:05:23,222 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    signal_title = parser_factory.get_parser.get_signal_title(id_of_requested_signal)
AttributeError: 'function' object has no attribute 'get_signal_title'
2021-02-18 22:05:23,225 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:05:23] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:05:58,848 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 22:05:58,849 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 22:05:58,864 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:06:03,280 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    signal_title = parser_factory.get_parser().get_signal_title(id_of_requested_signal)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 22:06:03,283 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:06:03] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:14:02,981 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-18 22:14:02,981 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-18 22:14:02,998 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:14:08,053 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    parser = parser_factory.get_parser()
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 22:14:08,057 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:14:08] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:14:15,368 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    parser = parser_factory.get_parser()
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 22:14:15,370 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:14:15] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:14:59,643 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 22:14:59,658 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:15:05,181 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    parser = parser_factory.get_parser()
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 22:15:05,184 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:15:05] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:16:59,412 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 22:16:59,428 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:17:05,712 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 21, in interpret_signal
    parser = parser_factory.get_parser()
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 22:17:05,715 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:17:05] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-18 22:17:47,381 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-18 22:17:47,396 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-18 22:17:52,847 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 21, in interpret_signal
    parser = parser_factory.get_parser()
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-18 22:17:52,850 - werkzeug - INFO - 127.0.0.1 - - [18/Feb/2021 22:17:52] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-19 05:47:37,409 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-19 05:47:37,423 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 05:47:41,925 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 20, in interpret_signal
    parser = parser_factory.get_parser()
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\parser_factory.py", line 17, in get_parser
    raise ValueError(self._signal_database_format)
ValueError: None
2021-02-19 05:47:41,929 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 05:47:41] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-19 05:49:30,912 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-19 05:49:30,913 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-19 05:49:30,930 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 05:49:34,744 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 21, in interpret_signal
    signal_title = parser_factory.get_signal_title(id_of_requested_signal)
AttributeError: 'ParserFactory' object has no attribute 'get_signal_title'
2021-02-19 05:49:34,748 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 05:49:34] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-19 05:53:19,472 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-19 05:53:19,472 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-19 05:53:19,486 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 05:53:24,591 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 21, in interpret_signal
    signal_title = parser_factory.get_signal_title(id_of_requested_signal)
AttributeError: 'ParserFactory' object has no attribute 'get_signal_title'
2021-02-19 05:53:24,594 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 05:53:24] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-19 05:54:05,784 - signal_interpreter_server.json_parser - INFO - Opening json database file: signal_database.json
2021-02-19 05:54:05,785 - signal_interpreter_server.json_parser - INFO - Loading json database file: signal_database.json
2021-02-19 05:54:05,803 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 05:54:09,693 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 05:54:09] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-19 05:56:06,200 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-19 05:56:06,216 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 05:56:17,220 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 05:56:17] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-19 05:56:22,898 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-19 05:56:22,899 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 25, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-19 05:56:22,900 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-19 05:56:22,900 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-19 05:56:22,901 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 05:56:22] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-19 06:06:06,348 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-19 06:06:06,365 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 06:06:11,187 - signal_interpreter_server.routes - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vdykin\.virtualenvs\signal-interpreter-server--w0D5r3E\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 22, in interpret_signal
    signal_database_format = parser.get_signal_database_format()
AttributeError: 'XmlParser' object has no attribute 'get_signal_database_format'
2021-02-19 06:06:11,189 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 06:06:11] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2021-02-19 06:06:54,365 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-19 06:06:54,380 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 06:06:58,574 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-19 06:06:58,575 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-19 06:06:58,575 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-19 06:06:58,576 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-19 06:06:58,576 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 06:06:58] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-19 11:22:14,773 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: signal_database.xml
2021-02-19 11:22:14,790 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-19 11:22:19,937 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-19 11:22:19,938 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-19 11:22:19,939 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 22 
2021-02-19 11:22:19,939 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-19 11:22:19,940 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 11:22:19] "[33mPOST / HTTP/1.1[0m" 404 -
2021-02-19 11:22:25,047 - werkzeug - INFO - 127.0.0.1 - - [19/Feb/2021 11:22:25] "[37mPOST / HTTP/1.1[0m" 200 -
2021-02-19 12:06:42,443 - signal_interpreter_server.json_parser - INFO - Opening json database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.json
2021-02-19 12:06:42,444 - signal_interpreter_server.json_parser - INFO - Loading json database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.json
2021-02-19 12:07:45,688 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.xml
2021-02-19 12:08:20,466 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.xml
2021-02-19 12:09:25,632 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.xml
2021-02-20 10:06:26,554 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:09:18,744 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:09:35,109 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:10:40,294 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:13:53,008 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:16:06,562 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:16:06,817 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:14,108 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:14,118 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:32,184 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:32,193 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:40,746 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:40,758 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:48,226 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:48,237 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:18:56,824 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:18:57,085 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:19:29,028 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:19:29,214 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:19:42,145 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:19:42,390 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:20:07,246 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:20:07,256 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:20:16,945 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:20:17,142 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:21:30,005 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:21:30,173 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:21:54,025 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:21:54,035 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:22:03,618 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:22:03,623 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:22:03,803 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:22:31,218 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:22:31,223 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:22:31,223 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:22:31,421 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:22:55,289 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:22:55,295 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 10:22:55,508 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file
2021-02-20 10:24:32,816 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:24:32,822 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:26:26,832 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:26:26,837 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:26:27,046 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 10:26:55,631 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:26:55,642 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 10:27:37,170 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:27:37,189 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 10:27:59,989 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:28:13,165 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 10:28:13,174 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 10:28:13,174 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 10:28:13,174 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 11:40:13,031 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 11:40:13,034 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 11:40:13,036 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 11:40:13,037 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 11:40:13,037 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 11:40:13,709 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 11:40:13,721 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 11:40:13,723 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 11:40:13,723 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 14:57:50,619 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 14:57:50,620 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 14:57:50,621 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 14:57:50,622 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:10:03,358 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:10:03,359 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:10:03,373 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:10:03,373 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:11:29,158 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:11:29,159 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:11:29,178 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:11:29,178 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:11:29,182 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:11:29,182 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 15:11:29,184 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:11:29,184 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:11:45,318 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:11:45,319 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:11:45,339 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:11:45,340 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:12:45,619 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:12:45,619 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:12:45,635 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:12:45,636 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:12:45,640 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:12:45,640 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 15:12:45,641 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:12:45,641 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:14:06,633 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:14:06,653 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:14:06,655 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:14:06,655 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:14:06,665 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:14:06,666 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 15:14:06,667 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:14:06,667 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:15:13,782 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:15:13,783 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:15:13,784 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:15:13,785 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:15:13,819 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:15:13,819 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 15:15:13,820 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:15:13,820 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:15:32,249 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 15:15:32,254 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 15:15:32,256 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 15:15:32,257 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 15:15:32,258 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:15:32,558 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 15:15:32,559 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 15:15:32,562 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:15:32,562 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:15:32,588 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:15:32,589 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 15:15:32,591 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 15:15:32,592 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 15:15:32,613 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 15:15:32,635 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 15:15:32,638 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 15:15:32,638 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:40:58,638 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file.xml
2021-02-20 15:40:58,639 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'path_to_file.xml' 
2021-02-20 15:40:58,640 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:41:54,546 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path_to_file.xml
2021-02-20 15:41:54,548 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'path_to_file.xml' 
2021-02-20 15:41:54,548 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 15:42:42,524 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: path/to/file.xml
2021-02-20 15:42:42,525 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'path/to/file.xml' 
2021-02-20 15:42:42,525 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:11:35,732 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:11:35,735 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 16:11:35,736 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:11:35,737 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 16:11:35,737 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:11:35,842 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:11:35,843 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 16:11:35,844 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:11:35,844 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:11:35,853 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:11:35,854 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 16:11:35,855 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:11:35,855 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:11:35,867 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 16:11:35,880 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 16:11:35,881 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 16:11:35,882 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:12:13,242 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:12:13,244 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 16:12:13,245 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:12:13,246 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 16:12:13,246 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:12:13,359 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:12:13,360 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 16:12:13,362 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:12:13,362 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:12:13,374 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:12:13,375 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 16:12:13,376 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:12:13,376 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:12:13,386 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 16:12:13,397 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 16:12:13,398 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 16:12:13,398 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:15:52,872 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:15:52,875 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 16:15:52,876 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:15:52,877 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 16:15:52,878 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:15:52,985 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:15:52,985 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 16:15:52,987 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:15:52,988 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:15:52,999 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:15:52,999 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 16:15:53,000 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:15:53,001 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:15:53,012 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 16:15:53,022 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 16:15:53,024 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 16:15:53,024 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:17:05,790 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.xml
2021-02-20 16:34:58,338 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.xml
2021-02-20 16:35:21,167 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\tests\integration\fixture\test_basic.xml
2021-02-20 16:46:49,186 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:46:49,190 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 16:46:49,191 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:46:49,192 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 16:46:49,193 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:46:49,660 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:46:49,661 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 16:46:49,664 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:46:49,664 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:46:49,675 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:46:49,676 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 16:46:49,677 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:46:49,677 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:46:49,689 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 16:46:49,700 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 16:46:49,702 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 16:46:49,703 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:47:11,769 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:47:11,774 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 16:47:11,776 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 16:47:11,777 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 16:47:11,777 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:47:11,926 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 16:47:11,927 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 16:47:11,930 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:47:11,931 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:47:11,942 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 16:47:11,943 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 16:47:11,944 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 16:47:11,944 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 16:47:11,955 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 16:47:11,968 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 16:47:11,970 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 16:47:11,970 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 17:09:39,791 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 17:09:39,796 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 17:09:39,797 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 17:09:39,798 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 17:09:39,798 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 17:09:39,927 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 17:09:39,928 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 17:09:39,930 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 17:09:39,931 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 17:09:39,945 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 17:09:39,946 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 17:09:39,946 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 17:09:39,947 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 17:09:39,958 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 17:09:39,969 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 17:09:39,971 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 17:09:39,971 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 17:13:51,249 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 17:13:51,252 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 17:13:51,253 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 17:13:51,254 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 17:13:51,254 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 17:13:51,376 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 17:13:51,376 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 17:13:51,378 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 17:13:51,379 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 17:13:51,392 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 17:13:51,393 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 17:13:51,394 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 17:13:51,394 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 17:13:51,407 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 17:13:51,418 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 17:13:51,420 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 17:13:51,420 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 17:37:32,815 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 17:37:32,819 - signal_interpreter_server.json_parser - INFO - Loading json database file: my_file_path
2021-02-20 17:37:32,821 - signal_interpreter_server.json_parser - INFO - Opening json database file: my_file_path
2021-02-20 17:37:32,822 - signal_interpreter_server.json_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path' 
2021-02-20 17:37:32,822 - signal_interpreter_server.json_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 17:37:32,949 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.JsonParserError'>
2021-02-20 17:37:32,950 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 26, in interpret_signal
    raise JsonParserError
signal_interpreter_server.exceptions.JsonParserError
2021-02-20 17:37:32,952 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 17:37:32,952 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 17:37:32,965 - signal_interpreter_server.routes - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
2021-02-20 17:37:32,966 - signal_interpreter_server.routes - ERROR - Exception occurred:  
Traceback (most recent call last):
  File "C:\Python27\PYTHON_COURSE_3\signal-interpreter-server\signal_interpreter_server\routes.py", line 29, in interpret_signal
    raise XmlParserError
signal_interpreter_server.exceptions.XmlParserError
2021-02-20 17:37:32,966 - signal_interpreter_server.routes - ERROR - Signal not found in database, signal ID: 27 
2021-02-20 17:37:32,967 - signal_interpreter_server.routes - INFO - Aborting server ...
2021-02-20 17:37:32,980 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path
2021-02-20 17:37:32,999 - signal_interpreter_server.xml_parser - INFO - Opening xml database file: my_file_path1
2021-02-20 17:37:33,001 - signal_interpreter_server.xml_parser - WARNING - Exception occurred [Errno 2] No such file or directory: 'my_file_path1' 
2021-02-20 17:37:33,002 - signal_interpreter_server.xml_parser - INFO - Raising exception: <class 'signal_interpreter_server.exceptions.XmlParserError'>
